---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .appName }}-deployment
  namespace: {{ .namespace }}
spec:
  replicas: {{ .replicas }}
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: {{ .appName }}
    spec:
      containers:
      - name: datalab-app
        image: {{ .image.name }}:{{ .image.version }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10