---
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}-service
  namespace: {{ .namespace }}
spec:
  ports:
  - name: http
    port: {{ .servicePort }}
    targetPort: {{ .targetPort }}
  selector:
    app: {{ .appName }}
  type: NodePort